server:
  port: 9090

person:
  name:
    first: Daniel
    last: Renato

spring:
  application:
    name: crud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/latihan4?currentSchema=public
    username: postgres
    password: Admin123
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 10
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include=*:
